name: tarot_noir
description: "A mystic app combining tarot readings, AI chatbot and NFT avatars."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: any

  cupertino_icons: ^1.0.8

  # HTTP / API
  http: ^1.5.0

  # Solana / SPL Token
  solana: ^0.32.0+1

  # Google AdMob
  google_mobile_ads: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/images/tarot_temp/
