import 'tarot_card.dart';

const majorArcana = <TarotCard>[
  TarotCard(
    '0',
    'Le Fou',
    '✦',
    'LE SAUT',
    'Le vide n’est pas une chute : c’est l’espace où ton prochain monde cherche sa forme.',
    '',
  ),
  TarotCard(
    'II',
    'La Grande Prêtresse',
    '☾',
    'LE SECRET',
    'Ne livre pas ta lumière à ceux qui ne savent regarder que les braises.',
    '',
  ),
  TarotCard(
    'XIII',
    'La Mort',
    '☠',
    'LA MUE',
    'Ce qui se termine libère une place sacrée. Laisse l’ancienne peau à la terre.',
    'assets/images/tarot_cards/arcane_majeur/La_Mort.png',
  ),
  TarotCard(
    'XVIII',
    'La Lune',
    '☾',
    'LE MIRAGE',
    'Ton intuition parle bas sous le bruit. Marche lentement, mais marche avec elle.',
    'assets/images/tarot_cards/arcane_majeur/La_lune.png',
  ),
  TarotCard(
    'XV',
    'Le Diable',
    '♜',
    'LA CHAÎNE',
    'Regarde la chaîne : elle est peut-être plus lâche que tu ne le crois.',
    'assets/images/tarot_cards/arcane_majeur/Le_Diable.jpeg',
  ),
  TarotCard(
    'XVII',
    'L’Étoile',
    '✧',
    'LA GUÉRISON',
    'Après la nuit, ton désir de vivre demeure une forme de magie.',
    'assets/images/tarot_cards/arcane_majeur/Le_Soleil.png',
  ),
  TarotCard(
    'VI',
    'Les Amants',
    '♡',
    'L’UNION',
    'Deux chemins peuvent se rencontrer sans perdre leur mystère.',
    'assets/images/tarot_cards/arcane_majeur/Les_Amants.png',
  ),
  TarotCard(
    'XXI',
    'Le Monde',
    '◎',
    'L’ACCOMPLISSEMENT',
    'Ce qui semblait dispersé retrouve son cercle. Une fin peut devenir une porte.',
    'assets/images/tarot_cards/arcane_majeur/Le_Monde.png',
  ),
  TarotCard(
    'I',
    'Le Bateleur',
    '✣',
    'L’ÉLAN',
    'Les outils sont là. Commence humblement, puis laisse le geste te révéler sa voie.',
    '',
  ),
  TarotCard(
    'III',
    'L’Impératrice',
    '♕',
    'LA CRÉATION',
    'Ce qui germe demande du soin, de la beauté et un espace où respirer.',
    '',
  ),
  TarotCard(
    'IV',
    'L’Empereur',
    '♔',
    'LA STRUCTURE',
    'Une limite juste peut devenir une protection, jamais une cage.',
    '',
  ),
  TarotCard(
    'V',
    'Le Pape',
    '✠',
    'LA TRANSMISSION',
    'Cherche un repère qui nourrit ta liberté au lieu de parler à ta place.',
    '',
  ),
  TarotCard(
    'VII',
    'Le Chariot',
    '✦',
    'LE PASSAGE',
    'Rassemble tes forces vers une seule direction et avance sans te trahir.',
    '',
  ),
  TarotCard(
    'VIII',
    'La Justice',
    '⚖',
    'L’ÉQUILIBRE',
    'Regarde les faits avec clarté : chaque choix construit son propre poids.',
    '',
  ),
  TarotCard(
    'IX',
    'L’Hermite',
    '☿',
    'LA LAMPE',
    'Le retrait choisi éclaire la prochaine marche. Garde une lumière, même petite.',
    'assets/images/tarot_cards/arcane_majeur/L_Hermite.png',
  ),
  TarotCard(
    'X',
    'La Roue de Fortune',
    '◉',
    'LE CYCLE',
    'Le mouvement revient. Accueille ce qui change et ancre ce qui compte.',
    '',
  ),
  TarotCard(
    'XI',
    'La Force',
    '♌',
    'LE COURAGE',
    'La force calme transforme davantage que la contrainte. Respire avant d’agir.',
    '',
  ),
  TarotCard(
    'XII',
    'Le Pendu',
    '⌇',
    'LE RENVERSEMENT',
    'Une pause volontaire peut montrer l’angle que l’élan ne voyait pas.',
    '',
  ),
  TarotCard(
    'XIV',
    'Tempérance',
    '⚗',
    'L’ALCHIMIE',
    'Dose, relie, ajuste. Ton équilibre se fabrique par de petits mélanges vrais.',
    '',
  ),
  TarotCard(
    'XVI',
    'La Maison Dieu',
    'ϟ',
    'LA FAILLE',
    'Une structure tombe parfois pour libérer la vérité qui voulait passer.',
    '',
  ),
  TarotCard(
    'XIX',
    'Le Soleil',
    '☀',
    'LA CLARTÉ',
    'Partage ce qui te rend vivant. Une joie honnête peut servir de boussole.',
    '',
  ),
  TarotCard(
    'XX',
    'Le Jugement',
    '⌁',
    'L’APPEL',
    'Une voix ancienne appelle une réponse neuve. Choisis ce qui t’appartient.',
    '',
  ),
];

const minorRanks = [
  'As',
  'Deux',
  'Trois',
  'Quatre',
  'Cinq',
  'Six',
  'Sept',
  'Huit',
  'Neuf',
  'Dix',
  'Valet',
  'Cavalier',
  'Reine',
  'Roi',
];

const minorSuits = [
  (name: 'Bâtons', symbol: '♣', theme: 'l’élan, l’action et la création'),
  (name: 'Coupes', symbol: '♡', theme: 'l’émotion, le lien et l’intuition'),
  (
    name: 'Épées',
    symbol: '♠',
    theme: 'la pensée, la parole et le discernement',
  ),
  (
    name: 'Deniers',
    symbol: '◇',
    theme: 'le corps, les ressources et le quotidien',
  ),
];

final minorArcana = <TarotCard>[
  for (final suit in minorSuits)
    for (var index = 0; index < minorRanks.length; index++)
      TarotCard(
        '${index + 1}-${suit.name}',
        '${minorRanks[index]} de ${suit.name}',
        suit.symbol,
        suit.name.toUpperCase(),
        'Cette carte parle de ${suit.theme}. Cherche le prochain geste simple qui respecte ton intention.',
        suit.name == 'Épées' && index == 0
            ? 'assets/images/tarot_cards/arcane_mineur/As_Dépées.png'
            : '',
      ),
];

final tarotDeck = <TarotCard>[...majorArcana, ...minorArcana];
